modLoader="javafml"
loaderVersion="[36,)"
license="Not specified"

[[mods]]
modId="promptium"
version="1.9.3"
displayName="promptium"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
logoFile="logo.png"
authors="ARG_R3coN"

[[dependencies.promptium]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




